/*
Copyright 2017 caicloud authors. All rights reserved.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apiv1 "k8s.io/client-go/pkg/api/v1"
)

// UpgraderType defines the type of upgrader.
type UpgraderType string

const (
	// DefaultUpgraderType defines a upgrader which updates release via default merge mode.
	// In default mode, upgrader merges config to release and upgrade release. Then terminate
	// current gray release.
	DefaultUpgraderType UpgraderType = "default"
)

// GrayReleasePhase defines the name of phases
type GrayReleasePhase string

const (
	// StartingGrayReleasePhase is the first stage of gray release. In this stage, Gray release
	// is starting the copy of release node and service proxy.
	StartingGrayReleasePhase GrayReleasePhase = "STARTING"
	// RunningGrayReleasePhase reveals that current gray relase is running.
	RunningGrayReleasePhase GrayReleasePhase = "RUNNING"
	// UpgradingGrayReleasePhase is shown when the upgrader has been specified. If a gray release
	// is in this stage, It's working as same as RunningGrayReleasePhase and attempting to upgrade
	// target release.
	UpgradingGrayReleasePhase GrayReleasePhase = "UPGRADING"
	// TerminationGrayReleasePhase is the status after UpgradingGrayReleasePhase. It shows the process
	// of upgrading succeeded and the gray release has stopt.
	TerminationGrayReleasePhase GrayReleasePhase = "TERMINATION"
	// ErrorGrayReleasePhase presents that something goes wrong and the gray release stopt. See
	// message for more infomation.
	ErrorGrayReleasePhase GrayReleasePhase = "ERROR"
)

// ProtocolType is the network type for ports
type ProtocolType string

const (
	ProtocolTypeHTTP  ProtocolType = "HTTP"
	ProtocolTypeHTTPS ProtocolType = "HTTPS"
	ProtocolTypeTCP   ProtocolType = "TCP"
	ProtocolTypeUDP   ProtocolType = "UDP"
)

// Upgrader defines a updrader for updating release
type Upgrader struct {
	Type UpgraderType `json:"type,omitempty"`
}

// Feature describes a proxy config for a service port
type Feature struct {
	// Weight is the only proxy way now. The value of weight should be [1,99].
	Weight *int32 `json:"weight,omitempty"`
}

// Port defines protocol and usable feature for a serviec port
type Port struct {
	// Port is the port number
	Port int32 `json:"port,omitempty"`
	// Protocol is the protocol used by the port
	Protocol ProtocolType `json:"protocol,omitempty"`
	// Feature is the port proxy option
	Feature Feature `json:"feature,omitempty"`
}

// Service describes a config of a service from release node
type Service struct {
	// Service is the name of the service
	Service string `json:"service,omitempty"`
	// Ports contains an array of port configs
	Ports []Port `json:"ports,omitempty"`
}

// GrayReleaseSpec is the specification of the desired behavior of the GrayRelease.
type GrayReleaseSpec struct {
	// Release is the release name from helm
	Release string `json:"release,omitempty"`
	// Path is the node path of release
	Path string `json:"path,omitempty"`
	// Config is the values of release node specified by Release and Path
	Config string `json:"config,omitempty"`
	// Services is an array of services in current release node
	Services []Service `json:"services,omitempty"`
	// Resources specify cpu/mem usage of current gray release
	Resources apiv1.ResourceRequirements `json:"resources,omitempty"`
	// Upgrader is an gray release upgrader. If it's not nil, The upgrader will
	// merge current config to target release and upgrade the release to
	// a new version. Then it will terminate current gray release.
	Upgrader *Upgrader `json:"upgrader,omitempty"`
}

// GrayReleaseStatus describes status of a gray release
type GrayReleaseStatus struct {
	// Phase is the stage of gray release
	Phase GrayReleasePhase `json:"phase,omitempty"`
	// Message contains infomation of current phase
	Message string `json:"message,omitempty"`
	// Manifests contains all kubernetes resources generated by Spec.Config
	Manifests string `json:"manifests,omitempty"`
}

// +genclient=true
// +genclientstatus=false

// GrayRelease describes a gray release with release config
type GrayRelease struct {
	metav1.TypeMeta `json:",inline"`
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Specification of the desired behavior of the GrayRelease.
	// +optional
	Spec GrayReleaseSpec `json:"spec,omitempty"`

	// Most recently observed status of the GrayRelease.
	// +optional
	Status GrayReleaseStatus `json:"status,omitempty"`
}

// GrayReleaseList describes an array of GrayRelease instances
type GrayReleaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`

	// Items is the list of gray releases
	Items []GrayRelease `json:"items"`
}

// ReleaseRollbackConfig describes the rollback config of a release
type ReleaseRollbackConfig struct {
	// The version to rollback to. If set to 0, rollbck to the last version.
	Version int32 `json:"version,omitempty"`
}

// ReleaseSpec describes the basic info of a release
type ReleaseSpec struct {
	// Description is the description of current release
	Description string
	// Template is an archived template data
	Template []byte `json:"template"`
	// Config is the config for parsing template
	Config string `json:"config"`
	// The config this release is rolling back to. Will be cleared after rollback is done.
	RollbackTo *ReleaseRollbackConfig `json:"rollbackTo,omitempty"`
}

type ReleaseConditionType string

const (
	ReleaseAvailable   ReleaseConditionType = "Available"
	ReleaseProgressing ReleaseConditionType = "Progressing"
	ReleaseFailure     ReleaseConditionType = "Failure"
)

// ReleaseHistorySpec describes the history info of a release
type ReleaseCondition struct {
	// Type of release condition.
	Type ReleaseConditionType `json:"type"`
	// Status of the condition, one of True, False, Unknown.
	Status apiv1.ConditionStatus `json:"status"`
	// Last time the condition transit from one status to another.
	LastTransitionTime metav1.Time `json:"lastTransitionTime,omitempty"`
	// Reason for the condition's last transition.
	Reason string `json:"reason,omitempty"`
	// Human readable message indicating details about last transition.
	Message string `json:"message,omitempty"`
}

// ResourceCounter is a status counter
type ResourceCounter struct {
	// Running is the count of running target
	Running int `json:"running"`
	// Mutating is the count of mutating target
	Mutating int `json:"mutating"`
	// Wrong is the count of wrong target
	Wrong int `json:"wrong"`
}

// ReleaseDetailStatus
type ReleaseDetailStatus struct {
	// Path is the path which resources from
	Path string
	// Resources contains a kind-counter map.
	// A kind should be a unique name of a group resources.
	Resources map[string]ResourceCounter
}

// ReleaseStatus describes the status of a release
type ReleaseStatus struct {
	// Version is the version of current release
	Version int32 `json:"version,omitempty"`
	// Manifest is the generated kubernetes resources from template
	Manifest string `json:"manifest,omitempty"`
	// LastUpdateTime is the last update time of current release
	LastUpdateTime metav1.Time `json:"lastUpdateTime,omitempty"`
	// Details contains all resources status of current release
	Details []ReleaseDetailStatus `json:"details,omitempty"`
	// Conditions is an array of current observed release conditions.
	Conditions []ReleaseCondition `json:"conditions,omitempty"`
}

// +genclient=true
// +genclientstatus=false

// Release describes a release wich chart and values
type Release struct {
	metav1.TypeMeta `json:",inline"`
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Specification of the desired behavior of the Release
	// +optional
	Spec ReleaseSpec `json:"spec,omitempty"`

	// Most recently observed status of the Release
	// +optional
	Status ReleaseStatus `json:"status,omitempty"`
}

// ReleaseList describes an array of Release instances
type ReleaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`

	// Items is the list of releases
	Items []Release `json:"items"`
}

// ReleaseHistorySpec describes the history info of a release
type ReleaseHistorySpec struct {
	// Description is the description of current history
	Description string `json:"description,omitempty"`
	// Version is the version of a history
	Version int32 `json:"version,omitempty"`
	// Template is an archived template data
	Template []byte `json:"template,omitempty"`
	// Config is the config for parsing template
	Config string `json:"config,omitempty"`
	// Manifest is the generated kubernetes resources from template
	Manifest string `json:"manifest,omitempty"`
}

// +genclient=true
// +genclientstatus=false

// ReleaseHistory describes a history of a release version
type ReleaseHistory struct {
	metav1.TypeMeta `json:",inline"`
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Specification of the desired behavior of the ReleaseHistory
	// +optional
	Spec ReleaseHistorySpec `json:"spec,omitempty"`
}

// ReleaseHistoryList describes an array of ReleaseHistory instances
type ReleaseHistoryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`

	// Items is the list of release histories
	Items []ReleaseHistory `json:"items"`
}
