/*
Copyright 2017 caicloud authors. All rights reserved.
*/

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apiv1 "k8s.io/client-go/pkg/api/v1"
)

// UpgraderType defines the type of upgrader.
type UpgraderType string

const (
	// DefaultUpgraderType defines a upgrader which updates release via default merge mode.
	// In default mode, upgrader merges config to release and upgrade release. Then terminate
	// current gray release.
	DefaultUpgraderType UpgraderType = "default"
)

// GrayReleasePhase defines the name of phases
type GrayReleasePhase string

const (
	// StartingGrayReleasePhase is the first stage of gray release. In this stage, Gray release
	// is starting the copy of release node and service proxy.
	StartingGrayReleasePhase GrayReleasePhase = "STARTING"
	// RunningGrayReleasePhase reveals that current gray relase is running.
	RunningGrayReleasePhase GrayReleasePhase = "RUNNING"
	// UpgradingGrayReleasePhase is shown when the upgrader has been specified. If a gray release
	// is in this stage, It's working as same as RunningGrayReleasePhase and attempting to upgrade
	// target release.
	UpgradingGrayReleasePhase GrayReleasePhase = "UPGRADING"
	// TerminationGrayReleasePhase is the status after UpgradingGrayReleasePhase. It shows the process
	// of upgrading succeeded and the gray release has stopt.
	TerminationGrayReleasePhase GrayReleasePhase = "TERMINATION"
	// ErrorGrayReleasePhase presents that something goes wrong and the gray release stopt. See
	// message for more infomation.
	ErrorGrayReleasePhase GrayReleasePhase = "ERROR"
)

// ProtocolType is the network type for ports
type ProtocolType string

const (
	ProtocolTypeHTTP  ProtocolType = "HTTP"
	ProtocolTypeHTTPS ProtocolType = "HTTPS"
	ProtocolTypeTCP   ProtocolType = "TCP"
	ProtocolTypeUDP   ProtocolType = "UDP"
)

// Upgrader defines a updrader for updating release
type Upgrader struct {
	Type UpgraderType `json:"type,omitempty"`
}

// Feature describes a proxy config for a service port
type Feature struct {
	// Weight is the only proxy way now. The value of weight should be [1,99].
	Weight *int32 `json:"weight,omitempty"`
}

// Port defines protocol and usable feature for a serviec port
type Port struct {
	// Port is the port number
	Port int32 `json:"port,omitempty"`
	// Protocol is the protocol used by the port
	Protocol ProtocolType `json:"protocol,omitempty"`
	// Feature is the port proxy option
	Feature Feature `json:"feature,omitempty"`
}

// Service describes a config of a service from release node
type Service struct {
	// Service is the name of the service
	Service string `json:"service,omitempty"`
	// Ports contains an array of port configs
	Ports []Port `json:"ports,omitempty"`
}

// GrayReleaseSpec is the specification of the desired behavior of the GrayRelease.
type GrayReleaseSpec struct {
	// Release is the release name from helm
	Release string `json:"release,omitempty"`
	// Path is the node path of release
	Path string `json:"path,omitempty"`
	// Config is the values of release node specified by Release and Path
	Config string `json:"config,omitempty"`
	// Services is an array of services in current release node
	Services []Service `json:"services,omitempty"`
	// Resources specify cpu/mem usage of current gray release
	Resources apiv1.ResourceRequirements `json:"resources,omitempty"`
	// Upgrader is an gray release upgrader. If it's not nil, The upgrader will
	// merge current config to target release and upgrade the release to
	// a new version. Then it will terminate current gray release.
	Upgrader *Upgrader `json:"upgrader,omitempty"`
}

// GrayReleaseStatus describes status of a gray release
type GrayReleaseStatus struct {
	// Phase is the stage of gray release
	Phase GrayReleasePhase `json:"phase,omitempty"`
	// Message contains infomation of current phase
	Message string `json:"message,omitempty"`
	// Manifests contains all kubernetes resources generated by Spec.Config
	Manifests string `json:"manifests,omitempty"`
}

// +genclient=true
// +genclientstatus=false

// GrayRelease describes a gray release with release config
type GrayRelease struct {
	metav1.TypeMeta `json:",inline"`
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty"`

	// Specification of the desired behavior of the GrayRelease.
	// +optional
	Spec GrayReleaseSpec `json:"spec,omitempty"`

	// Most recently observed status of the GrayRelease.
	// +optional
	Status GrayReleaseStatus `json:"status,omitempty"`
}

// GrayReleaseList describes an array of GrayRelease instances
type GrayReleaseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`

	// Items is the list of gray releases
	Items []GrayRelease `json:"items"`
}
