/*
Copyright 2017 caicloud authors. All rights reserved.
*/

// This file was automatically generated by lister-gen

package v1alpha1

// GrayReleaseListerExpansion allows custom methods to be added to
// GrayReleaseLister.
type GrayReleaseListerExpansion interface{}

// GrayReleaseNamespaceListerExpansion allows custom methods to be added to
// GrayReleaseNamespaceLister.
type GrayReleaseNamespaceListerExpansion interface{}
