/*
Copyright 2017 caicloud authors. All rights reserved.
*/

// This file was automatically generated by lister-gen

package v1alpha1

// GrayReleaseListerExpansion allows custom methods to be added to
// GrayReleaseLister.
type GrayReleaseListerExpansion interface{}

// GrayReleaseNamespaceListerExpansion allows custom methods to be added to
// GrayReleaseNamespaceLister.
type GrayReleaseNamespaceListerExpansion interface{}

// ReleaseListerExpansion allows custom methods to be added to
// ReleaseLister.
type ReleaseListerExpansion interface{}

// ReleaseNamespaceListerExpansion allows custom methods to be added to
// ReleaseNamespaceLister.
type ReleaseNamespaceListerExpansion interface{}

// ReleaseHistoryListerExpansion allows custom methods to be added to
// ReleaseHistoryLister.
type ReleaseHistoryListerExpansion interface{}

// ReleaseHistoryNamespaceListerExpansion allows custom methods to be added to
// ReleaseHistoryNamespaceLister.
type ReleaseHistoryNamespaceListerExpansion interface{}
